# yaml-language-server: $schema=https://gh-dash.dev/schema.json

# Reminders sections configuration
[[remindersSections]]
title = "All Reminders"
filters = ""
[remindersSections.layout]
[remindersSections.layout.list]
width = 20
[remindersSections.layout.dueIn]
width = 15
[remindersSections.layout.date]
width = 18
[remindersSections.layout.priority]
width = 10
[remindersSections.layout.completed]
width = 10

# Default settings
[defaults]
view = "reminders"
remindersLimit = 20
refetchIntervalMinutes = 0
dateFormat = "relative"

[defaults.preview]
open = true
width = 50

[defaults.layout.reminders]
[defaults.layout.reminders.title]
width = 30
[defaults.layout.reminders.list]
width = 20
[defaults.layout.reminders.dueIn]
width = 15
[defaults.layout.reminders.date]
width = 18
[defaults.layout.reminders.priority]
width = 10
[defaults.layout.reminders.completed]
width = 10

# List colors for visual organization
[listColors]
"Work" = "#FF6B6B"
"Personal" = "#4ECDC4"
"Shopping" = "#45B7D1"
"Health" = "#96CEB4"
"Travel" = "#FFEAA7"

# Keybindings
[[keybindings.universal]]
key = "q"
builtin = "quit"

[[keybindings.universal]]
key = "ctrl+c"
builtin = "quit"

[[keybindings.reminders]]
key = "r"
builtin = "refresh"

[[keybindings.reminders]]
key = "R"
builtin = "refreshAll"

[[keybindings.reminders]]
key = "s"
builtin = "search"

[[keybindings.reminders]]
key = "?"
builtin = "help"

# Theme configuration
[theme.ui]
sectionsShowCount = true
[theme.ui.table]
showSeparator = true
compact = false

[theme.colors.text]
primary = "#E2E1ED"
secondary = "#666CA6"
inverted = "#242347"
faint = "#B0B3BF"
warning = "#E0AF68"
success = "#3DF294"
error = "#FF6B6B"

[theme.colors.background]
selected = "#1B1B33"

[theme.colors.border]
primary = "#383B5B"
secondary = "#39386B"
faint = "#2B2B40"

# Other settings
confirmQuit = false
smartFilteringAtLaunch = true