# Default configuration file for reminders-dashboard
# This represents the default values used when no custom config is provided

confirmQuit = false
smartFilteringAtLaunch = true

[defaults]
remindersLimit = 20
view = "reminders"
refetchIntervalMinutes = 0
dateFormat = ""

[defaults.preview]
open = true
width = 50

[defaults.layout.reminders.title]
width = 30

[defaults.layout.reminders.list]
width = 20

[defaults.layout.reminders.dueIn]
width = 15

[defaults.layout.reminders.date]
width = 16

[defaults.layout.reminders.priority]
width = 10

[defaults.layout.reminders.completed]
width = 10

[[remindersSections]]
title = "All Reminders"
filters = ""

[theme.ui]
sectionsShowCount = true

[theme.ui.table]
showSeparator = true
compact = false

# listColors is empty by default
[listColors]

# keybindings are empty by default (uses built-in bindings)
[[keybindings.universal]]

[[keybindings.reminders]]