# Default configuration file for reminders-dashboard
# This represents the default values used when no custom config is provided

confirmQuit = false
smartFilteringAtLaunch = true

[defaults]
remindersLimit = 20
view = "reminders"
refetchIntervalMinutes = 0
dateFormat = ""

[defaults.preview]
open = true
width = 50

[defaults.layout.reminders.title]
width = 30

[defaults.layout.reminders.list]
width = 20

[defaults.layout.reminders.dueIn]
width = 15

[defaults.layout.reminders.date]
width = 16

[defaults.layout.reminders.priority]
width = 10

[defaults.layout.reminders.completed]
width = 10

[[remindersSections]]
title = "All Reminders"
filters = ""

[theme.ui]
sectionsShowCount = true

[theme.ui.table]
showSeparator = true
compact = false

# Theme colors - based on Catppuccin Frappe palette
[theme.colors.text]
primary = "#c6d0f5"      # Text - main text color
secondary = "#b5bfe2"    # Subtext 1 - secondary text
faint = "#a5adce"        # Subtext 0 - faint/muted text
inverted = "#303446"     # Base - inverted text on light backgrounds
success = "#a6d189"      # Green - success messages
warning = "#ef9f76"      # Peach - warnings
error = "#e78284"        # Red - errors

[theme.colors.background]
selected = "#414559"     # Surface 0 - selected/highlighted background

[theme.colors.border]
primary = "#626880"      # Surface 2 - primary borders
secondary = "#51576d"    # Surface 1 - secondary borders
faint = "#414559"        # Surface 0 - faint borders

# listColors is empty by default
[listColors]

# keybindings are empty by default (uses built-in bindings)
[[keybindings.universal]]

[[keybindings.reminders]]